# CMake generated Testfile for 
# Source directory: /home/dell/ZDisk/Workspace/abc/t/nanomsg
# Build directory: /home/dell/ZDisk/Workspace/abc/t/nanomsg
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(inproc "/home/dell/ZDisk/Workspace/abc/t/nanomsg/inproc" "12100")
set_tests_properties(inproc PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;402;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(inproc_shutdown "/home/dell/ZDisk/Workspace/abc/t/nanomsg/inproc_shutdown" "12110")
set_tests_properties(inproc_shutdown PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;403;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(ipc "/home/dell/ZDisk/Workspace/abc/t/nanomsg/ipc" "12120")
set_tests_properties(ipc PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;404;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(ipc_shutdown "/home/dell/ZDisk/Workspace/abc/t/nanomsg/ipc_shutdown" "12130")
set_tests_properties(ipc_shutdown PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;405;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(ipc_stress "/home/dell/ZDisk/Workspace/abc/t/nanomsg/ipc_stress" "12140")
set_tests_properties(ipc_stress PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;406;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(tcp "/home/dell/ZDisk/Workspace/abc/t/nanomsg/tcp" "12150")
set_tests_properties(tcp PROPERTIES  TIMEOUT "20" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;407;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(tcp_shutdown "/home/dell/ZDisk/Workspace/abc/t/nanomsg/tcp_shutdown" "12160")
set_tests_properties(tcp_shutdown PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;408;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(ws "/home/dell/ZDisk/Workspace/abc/t/nanomsg/ws" "12170")
set_tests_properties(ws PROPERTIES  TIMEOUT "20" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;409;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(pair "/home/dell/ZDisk/Workspace/abc/t/nanomsg/pair" "12180")
set_tests_properties(pair PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;412;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(pubsub "/home/dell/ZDisk/Workspace/abc/t/nanomsg/pubsub" "12190")
set_tests_properties(pubsub PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;413;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(reqrep "/home/dell/ZDisk/Workspace/abc/t/nanomsg/reqrep" "12200")
set_tests_properties(reqrep PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;414;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(pipeline "/home/dell/ZDisk/Workspace/abc/t/nanomsg/pipeline" "12210")
set_tests_properties(pipeline PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;415;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(survey "/home/dell/ZDisk/Workspace/abc/t/nanomsg/survey" "12220")
set_tests_properties(survey PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;416;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(bus "/home/dell/ZDisk/Workspace/abc/t/nanomsg/bus" "12230")
set_tests_properties(bus PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;417;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(async_shutdown "/home/dell/ZDisk/Workspace/abc/t/nanomsg/async_shutdown" "12240")
set_tests_properties(async_shutdown PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;420;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(block "/home/dell/ZDisk/Workspace/abc/t/nanomsg/block" "12250")
set_tests_properties(block PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;421;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(term "/home/dell/ZDisk/Workspace/abc/t/nanomsg/term" "12260")
set_tests_properties(term PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;422;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(timeo "/home/dell/ZDisk/Workspace/abc/t/nanomsg/timeo" "12270")
set_tests_properties(timeo PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;423;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(iovec "/home/dell/ZDisk/Workspace/abc/t/nanomsg/iovec" "12280")
set_tests_properties(iovec PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;424;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(msg "/home/dell/ZDisk/Workspace/abc/t/nanomsg/msg" "12290")
set_tests_properties(msg PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;425;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(prio "/home/dell/ZDisk/Workspace/abc/t/nanomsg/prio" "12300")
set_tests_properties(prio PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;426;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(poll "/home/dell/ZDisk/Workspace/abc/t/nanomsg/poll" "12310")
set_tests_properties(poll PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;427;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(device "/home/dell/ZDisk/Workspace/abc/t/nanomsg/device" "12320")
set_tests_properties(device PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;428;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(device4 "/home/dell/ZDisk/Workspace/abc/t/nanomsg/device4" "12330")
set_tests_properties(device4 PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;429;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(device5 "/home/dell/ZDisk/Workspace/abc/t/nanomsg/device5" "12340")
set_tests_properties(device5 PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;430;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(device6 "/home/dell/ZDisk/Workspace/abc/t/nanomsg/device6" "12350")
set_tests_properties(device6 PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;431;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(device7 "/home/dell/ZDisk/Workspace/abc/t/nanomsg/device7" "12360")
set_tests_properties(device7 PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;432;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(emfile "/home/dell/ZDisk/Workspace/abc/t/nanomsg/emfile" "12370")
set_tests_properties(emfile PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;433;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(domain "/home/dell/ZDisk/Workspace/abc/t/nanomsg/domain" "12380")
set_tests_properties(domain PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;434;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(trie "/home/dell/ZDisk/Workspace/abc/t/nanomsg/trie" "12390")
set_tests_properties(trie PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;435;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(list "/home/dell/ZDisk/Workspace/abc/t/nanomsg/list" "12400")
set_tests_properties(list PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;436;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(hash "/home/dell/ZDisk/Workspace/abc/t/nanomsg/hash" "12410")
set_tests_properties(hash PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;437;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(stats "/home/dell/ZDisk/Workspace/abc/t/nanomsg/stats" "12420")
set_tests_properties(stats PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;438;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(symbol "/home/dell/ZDisk/Workspace/abc/t/nanomsg/symbol" "12430")
set_tests_properties(symbol PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;439;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(separation "/home/dell/ZDisk/Workspace/abc/t/nanomsg/separation" "12440")
set_tests_properties(separation PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;440;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(zerocopy "/home/dell/ZDisk/Workspace/abc/t/nanomsg/zerocopy" "12450")
set_tests_properties(zerocopy PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;441;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(shutdown "/home/dell/ZDisk/Workspace/abc/t/nanomsg/shutdown" "12460")
set_tests_properties(shutdown PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;442;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(cmsg "/home/dell/ZDisk/Workspace/abc/t/nanomsg/cmsg" "12470")
set_tests_properties(cmsg PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;443;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(bug328 "/home/dell/ZDisk/Workspace/abc/t/nanomsg/bug328" "12480")
set_tests_properties(bug328 PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;444;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(bug777 "/home/dell/ZDisk/Workspace/abc/t/nanomsg/bug777" "12490")
set_tests_properties(bug777 PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;445;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(ws_async_shutdown "/home/dell/ZDisk/Workspace/abc/t/nanomsg/ws_async_shutdown" "12500")
set_tests_properties(ws_async_shutdown PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;446;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(reqttl "/home/dell/ZDisk/Workspace/abc/t/nanomsg/reqttl" "12510")
set_tests_properties(reqttl PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;447;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
add_test(surveyttl "/home/dell/ZDisk/Workspace/abc/t/nanomsg/surveyttl" "12520")
set_tests_properties(surveyttl PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;396;add_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;448;add_libnanomsg_test;/home/dell/ZDisk/Workspace/abc/t/nanomsg/CMakeLists.txt;0;")
subdirs("src")
